### ISSUE TITLE
Project List

### ISSUE THREAD

**Issue by Nought57** [TesseractTeam/Tesseract#108]
This is a Planning document. (public post)
If you are a member of Tesseract, you can edit it freely.
#### Todo
- [ ] Original Redstone (config version)
- [ ] Fix enchant tables & anvils correctly
- [ ] Major code cleanup
- [x] 1.0.0 Items
- [ ] 1.0.0 Blocks
- [ ] 1.0.0 Entities
- [ ] 1.0.0 Tiles
#### Enhancement
- [ ] Name with spaces
- [ ] Original MobAI
- [x] RakLib disable
- [ ] Lingering Potion
- [ ] Ender Chest
- [ ] Minecart (Redstone)
- [ ] Boat
#### Bug
- [ ] World Teleport Bug (Chunk)
- [ ] Potions causing knockback Bug
- [x] Biome generator Bug
- [x] Item Drop Bug
- [x] Command Usage Bug (Player Command only)
#### github
- [x] Jenkins Build Error

**Comment by xZeroMCPE** [comment]
Got Enderchest working, but where would be a good place to save player items?

**Comment by ankitmaharjan252** [comment]
Save it where the chest saves!

**Comment by Nought57** [comment]
I have one idea. I'm thinking of using player.dat file.

**Comment by xZeroMCPE** [comment]
@Nought57 Yeah, nice idea.

**Comment by ankitmaharjan252** [comment]
I think normal chests also save their!

**Comment by xZeroMCPE** [comment]
@ankitmaharjan252 Enderchest aren't like normal chests....

They don't combine into (2) when multiple chests are placed next to each other, and Enderchest has a unique inventory for each player....

**Comment by IISweePII** [comment]
For the minecart bug, I noticed it does level itself after you go on it, but you get booted to the ground, causes a uninitialized error/notice to happen

**Comment by AppleDevelops** [comment]
I believe I've added all 1.0.0 Items. Please help me confirm this.

**Comment by Nought57** [comment]
@AppleDevelops  Of course. I will do anything I can.

**Comment by AppleDevelops** [comment]
Still missing EnderChest and a few other 1.0 blocks

**Comment by remotevase** [comment]
This issue is now under the Projects tab located here:
https://github.com/TesseractTeam/Tesseract/projects/1
