### ISSUE TITLE
API 4.0.0

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#482]
Hey everyone, if you haven't noticed, we've started making the biggest api change in Tesseract's history, this very well could break plugins. 

**TODO:**

- [x] Move the tesseract.yml to pocketmine.yml
- [ ] Effects to json
- [ ] HIGH PRIORITY: Fix outdated client issue.
- [ ] Redo lang files
- [ ] Resource packs
- [ ] Relocation of entity files
- [ ] Move certain blocks and items to json
- [ ] Cleanup mess I added in Player.php
- [ ] Performance changes

**Notice:**

We also need a few testers, You can test the API 4.0.0 by switching to it branch. Please do note that we're planing on fixing a lot of things, so it should not be use for production yet. But again, good luck testing, ( - xZeroMCPE)

**Comment by Prisane** [comment]
Do you think to add it again beacon?

**Comment by mote166** [comment]
i really don't suggest doing so cuz it may affect many essential plugins which are abandoned by thier developers and people who can't code will definitely get troubles .

**Comment by Driesboy** [comment]
i will help you testing 👍 i have a linux, mac osx and a windows
say me if you need a tester :)

**Comment by xZeroMCPE** [comment]
@Driesboy The branch is open, just download and test it / look for bugs!

**Comment by MCPEGamerJPatGitHub** [comment]
when it's somewhat making shape, i'll test this

**Comment by xZeroMCPE** [comment]
API 4.0.0 branch commits has been removed, I will be doing everything all over. 

Also,

@Nought57  Add resource pack support to it. Test it though.. Making sure clients can join, and it works!

**Comment by CesarDevelop** [comment]
Omg... You would first get to 3.0.0.0.
