### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#9]
- [ ] Rewrite redstone system
- [ ] Implement pastebin.com or (github gist) api (sends crash dumps - Better then spamming a issue)
- [ ] Fix potions causing knockback
- [ ] Major code cleanup
- [ ] Fix Enchanting Tables and Anvils Correctly.
- [ ] Add more 1.0.0 blocks/tiles/entities

**Comment by IISweePII** [comment]
If we do manage to make a good AI for mobs, it will be great, we can also add it to the config :p

**Comment by xZeroMCPE** [comment]
ye

**Comment by IISweePII** [comment]
For Mob AI:
- [ ] Fix Animation of all mobs
- [ ] Correct leveling for some entities
      - [ ] Strays
      - [ ] Witches
      - [ ] Squids
- [ ] Add mobs that don't spawn yet
      - [ ] Wither Skeleton
      - [ ] Skeleton Horse
      - [ ] Donkey
      - [ ] Horse
      - [ ] Mule
      - [ ] Zombie Horse
- [ ] Fix gravity of some mobs
      - [ ] Villagers

**Comment by xZeroMCPE** [comment]
I don't seem to have permission on here to create files, etc. I know i'm a "Member" but again, fix the permissions. Or promote me to a higher one...

**Comment by TheAppleGamer** [comment]
@xZeroMCPE I keep forgetting to add everyone to Owner there you go

**Comment by xZeroMCPE** [comment]
@TheAppleGamer Don't add "everyone" to "owner", only add those you trust. :)

**Comment by TheAppleGamer** [comment]
@xZeroMCPE I consider every member a person I trust

**Comment by xZeroMCPE** [comment]
@TheAppleGamer Oh, okay. Never knew that.

**Comment by xZeroMCPE** [comment]
I've added 1 todo item(s) on the list.

**Comment by TheAppleGamer** [comment]
Adding Genisys old MobAI on a separate branch

**Comment by TheAppleGamer** [comment]
Added some new things

**Comment by Pogogo007** [comment]
Just added a new thing

**Comment by Pogogo007** [comment]
Just added a new thing again. @AppleDevelops

**Comment by austina1212** [comment]
Maybe add all enchantments up too 100 so it works on OP factions really well? (Cause my factions server, Stcraft is having issues with kits being buggy, because of enchantments not setup to work that high!)

**Comment by NycuRO** [comment]
Enchanting fix: 
https://github.com/Hydreon/Steadfast2/commit/7ba05d8fe2ca63d1c783ec98e363872c8d14ab31

https://github.com/Hydreon/Steadfast2/commit/2b35a061725765e22141e2059b84842c038862c5

https://github.com/Hydreon/Steadfast2/commit/413bc86e515e403419aa758d3faa35e2484ccd30

https://github.com/Hydreon/Steadfast2/commit/a3377826add946f1f1ab17242caa97c15932e6d7

https://github.com/Hydreon/Steadfast2/commit/cd1574df297bbee6d71e8998a323fd520e3f31f2

https://github.com/Hydreon/Steadfast2/commit/e9ed289453fd4b1bcabe86068ab1470fb9d1bcd7

https://github.com/Hydreon/Steadfast2/commit/459844b6bd1757ce15e2c37bd89cd6cf63caa1ea

Fix hotbar in win10:

https://github.com/Hydreon/Steadfast2/commit/ebaa3df4293649913f6657c78693c71774e5ecdd

**Comment by Infernus102** [comment]
Priority should be the #86 issue because server freezes up and CPU load increases to 100% when more than 5 players join in and login

**Comment by xZeroMCPE** [comment]
@Infernus102 Yeah, that's right...
